"use client";

import { useQuery } from "@tanstack/react-query";
import api from "@/services/api";
import { Loader2, Printer, ArrowLeft } from "lucide-react";
import { Button } from "@/components/ui/button";
import { useParams, useRouter } from "next/navigation";
import { useRef } from "react";
import Image from "next/image";

export default function BadgePrintPage() {
  const params = useParams();
  const router = useRouter();
  const printRef = useRef<HTMLDivElement>(null);

  const { data: visitor, isLoading } = useQuery({
    queryKey: ['visitor', params.visitorId],
    queryFn: async () => {
      const response = await api.get(`/visitors/${params.visitorId}`);
      return response.data.data;
    },
  });

  const handlePrint = () => {
    window.print();
  };

  if (isLoading) return (
    <div className="min-h-screen flex items-center justify-center bg-slate-950">
      <Loader2 className="h-8 w-8 animate-spin text-primary" />
    </div>
  );

  return (
    <div className="min-h-screen bg-slate-900 pb-20">
      {/* Controls - Hidden on Print */}
      <div className="sticky top-0 bg-slate-950/80 backdrop-blur-md border-b border-white/5 py-4 px-8 flex justify-between items-center z-50 print:hidden">
        <Button variant="ghost" onClick={() => router.back()} className="text-muted-foreground">
          <ArrowLeft className="mr-2 h-4 w-4" />
          Back to List
        </Button>
        <div className="flex gap-4">
          <div className="text-xs text-muted-foreground bg-white/5 px-3 py-2 rounded-lg border border-white/5">
            Format: Standard Thermal (4x6)
          </div>
          <Button onClick={handlePrint} className="bg-indigo-600 hover:bg-indigo-700 shadow-xl shadow-indigo-600/20">
            <Printer className="mr-2 h-4 w-4" />
            Print Badge
          </Button>
        </div>
      </div>

      {/* Badge Content */}
      <div className="max-w-md mx-auto mt-12 px-4 print:mt-0 print:px-0">
        <div 
          ref={printRef}
          className="bg-white text-black p-8 rounded-2xl shadow-2xl border border-gray-200 aspect-[4/6] flex flex-col items-center justify-between text-center print:shadow-none print:border-none print:rounded-none selection:bg-transparent"
        >
          {/* Header */}
          <div className="w-full space-y-2">
            <h2 className="text-2xl font-black tracking-tighter text-indigo-600 uppercase">Expo 2026</h2>
            <div className="h-1 w-20 bg-indigo-600 mx-auto rounded-full" />
            <p className="text-[10px] font-bold text-gray-400 tracking-[0.2em]">{visitor.eventId?.name || 'VisiTrack Event'}</p>
          </div>

          {/* Body */}
          <div className="flex-1 flex flex-col items-center justify-center space-y-6">
            <div className="space-y-1">
              <h1 className="text-4xl font-extrabold uppercase leading-none">{visitor.name}</h1>
              <p className="text-sm font-medium text-gray-500">{visitor.email}</p>
            </div>

            <div className="p-4 bg-gray-50 rounded-2xl border border-gray-100 flex items-center justify-center">
                <Image 
                  src={`https://api.qrserver.com/v1/create-qr-code/?size=300x300&data=${visitor.v_id}`} 
                  alt="Visitor QR" 
                  width={300}
                  height={300}
                  className="w-full h-full object-contain"
                />
            </div>

            <div className="bg-indigo-600 text-white px-6 py-2 rounded-full font-black tracking-widest text-sm italic">
              VISITOR
            </div>
          </div>

          {/* Footer */}
          <div className="w-full pt-6 border-t border-gray-100 space-y-1">
            <p className="text-[10px] font-bold text-gray-400">ID: {visitor._id.slice(-12).toUpperCase()}</p>
            <p className="text-[8px] text-gray-300">Generated by VisiTrack Smart System</p>
          </div>
        </div>
      </div>

      <style jsx global>{`
        @media print {
          @page {
            size: auto;
            margin: 0mm;
          }
          body {
            background: white !important;
            margin: 0;
            padding: 0;
          }
        }
      `}</style>
    </div>
  );
}
